version: '3'

# Define all the services
services:
  # Archive frontend
  archive-browser:
    build: ./archive-browser
    environment:
      # TODO: Update this URL to point to your fileserver.
      # Make sure it's accessible from your browser
      - DRIVE_BASE_URL=https://${SERVER_HOSTNAME}:8080
      - ES_BACKEND_URL=http://elastic:9200
      - ENABLE_SIGN_URLS=false
    networks:
      - ragtag-archive
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
    depends_on:
      elastic:
        condition: service_healthy
    entrypoint: "bash /app/entrypoint.sh"
    command: "yarn start"


  # Elasticsearch database
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - ragtag-archive
    healthcheck:
      test: curl -s http://elastic:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  # Nginx file server
  nginx:
    image: nginx:stable
    volumes:
      # TODO: update mount point to where your files will be stored
      - nginxdata:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${SECRETS_LOCATION}:/etc/nginx/ssl
      - /media/tenvinc/a00e3fc5-9ff4-4909-a253-c9ecebb2faaa/Hololive/MinatoAqua:/usr/share/nginx/archive
    ports:
      - 3000:3000    # Frontend
      - 8080:8080    # Nginx file server
      - 9200:9200    # Elastic search
    depends_on:
      archive-browser:
        condition: service_started
    networks:
      - ragtag-archive

volumes:
  esdata:
    driver: local
  nginxdata:
    driver: local

networks:
  ragtag-archive:
    driver: bridge
