version: '3'

# Define all the services
services:
  # Archive frontend
  archive-browser:
    build: ./archive-browser
    environment:
      # TODO: Update this URL to point to your fileserver.
      # Make sure it's accessible from your browser
      - DRIVE_BASE_URL=http://localhost:8080
      - ES_BACKEND_URL=http://elastic:9200
      - ENABLE_SIGN_URLS=false
    ports:
      - 3000:3000
    networks:
      - ragtag-archive

  # Elasticsearch database
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ragtag-archive

  # Nginx file server
  nginx:
    image: nginx:stable
    volumes:
      # TODO: update mount point to where your files will be stored
      - nginxdata:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - ragtag-archive

volumes:
  esdata:
    driver: local
  nginxdata:
    driver: local

networks:
  ragtag-archive:
    driver: bridge
